<Project Sdk="Microsoft.NET.Sdk">

<PropertyGroup>
		<!-- On définit les versions Android AVANT tout le reste -->
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">31.0</SupportedOSPlatformVersion>
		<TargetPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">36.0</TargetPlatformVersion>

		<TargetFrameworks>net10.0-android36.0;net10.0-ios;net10.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net10.0-windows10.0.19041.0</TargetFrameworks>

		<OutputType>Exe</OutputType>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<AssemblyName>MusicScoreManager</AssemblyName>
		<ApplicationTitle>MusicScoreManager</ApplicationTitle>
		<ApplicationId>com.audiothor.musicscoremanager</ApplicationId>
		<ApplicationIdGuid>3E6F90A1-B8D2-4E05-98E3-C9E2BCBE0F1F</ApplicationIdGuid>

		<ApplicationDisplayVersion>1.5.0</ApplicationDisplayVersion>
		<ApplicationVersion>1500</ApplicationVersion>
		<!-- Version actuelle : v1.5.0 "Stable UI & Stickers" -->
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		
		<!-- Support universel : ARM32, ARM64 et x64 (émulateur) -->
		<RuntimeIdentifiers Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">android-arm;android-arm64;android-x64</RuntimeIdentifiers>
		<AndroidSupportedAbis Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">armeabi-v7a;arm64-v8a;x86_64</AndroidSupportedAbis>
	</PropertyGroup>

	<!-- Branding : Icône et Splash Screen (Logo rectangulaire et large) -->
	<ItemGroup>
		<MauiIcon Include="Resources\AppIcon\appicon.png" ForegroundScale="0.65" Color="#121212" />
		<MauiSplashScreen Include="Resources\Splash\app_splash_padded.png" Color="#121212" BaseSize="512,512" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="14.1.0" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="10.0.41" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.0" />
		<PackageReference Include="Plugin.Maui.Audio" Version="4.0.0" />
		<PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
		<PackageReference Include="CommunityToolkit.Maui.MediaElement" Version="9.0.0" />
	</ItemGroup>

	<ItemGroup>
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

</Project>